### ISSUE TITLE
Some Ask Applicant Type very Higher Ed specific

### ISSUE THREAD

**Issue by dwhitig** [SFDO-Community-Sprints/Summit-Events-App#393]
The Ask Applicant Type field on the Event Standard Option | Labels section has three picklist items that are very Higher Ed specific.  Can these be deactivated by default as not to confuse that are using the product that are not higher ed?

![image](https://user-images.githubusercontent.com/4521914/167025031-a56273d8-b05d-4cd1-983e-ae52fbe284b2.png)

**Expected behavior**

**Comment by rdblake21** [comment]
@dwhitig We can't deactivate these values without removing them entirely. Because there is a hardcoded element in the code, I've updated the documentation as a Post-Installation Consideration to review and deactivate values your organization won't utilize.  This will also be called out in the page layout considerations to remove any industry specific fields, like Ask Applicant Type.

https://github.com/SFDO-Community-Sprints/summit-events-app-documentation/blob/main/docs/Getting-Started/post-install-consideration.md

**Comment by dwhitig** [comment]
Okay, makes sense
