### ISSUE TITLE
If text response in an additional question (standard, legacy functionality) exceeds 1,000 characters, the registration does not process on the backend, no error on the registration page.

### ISSUE THREAD

**Issue by walt0019** [SFDO-Community-Sprints/Summit-Events-App#397]
**Describe the bug**
If text response in an additional question (standard, legacy functionality) exceeds 1,000 characters, the registration does not process on the backend, no error on the registration page.

**To Reproduce**
1. Go to event using a Add Info Question 1.
2. Fill out Summit Event registration form, but exceed a response more than 1000 characters.
3. Complete registration and the page lands on the Confirmation Page.
4. Unable to see registration on the Event Instance.

**Expected behavior**
Expected to see an error message on the page that the response exceeded a character limit.  User was also hoping to see a character counter on the field.  Or also hoping the registration is in a started status or a registration in registered status with their response trimmed.

**Comment by rdblake21** [comment]
@walt0019 the character limit on the Add_Info_Answer_1__c field is 1000 characters, so the error makes sense.  Because the error occured before the registration process, that impacted the ability for the registrant to have a started status.

I remember this happening with UST Events, we increased the length on the Event Registration.

Adding the error message or character counter would be new functionality for those fields, so I'm thinking we can increase the length and then turn this into an enhancement.

Thoughts?

**Comment by rdblake21** [comment]
I increase the limit to 5000 and also updated the help text to set expectations

**Comment by walt0019** [comment]
Thanks, @rdblake21.  I didn't look at increasing the Length of the field, I guess I assumed it was locked as a managed package, but it's editable.  Thanks!

**Comment by walt0019** [comment]
Check that, @rdblake21.  The field looks editable but it doesn't take a change from the end user.  We'll need a deploy to update that field length.

**Comment by rdblake21** [comment]
This just got merged, so you should be able to refresh your dev org or create a new one and see the increased field size and updated help text to call out the limit being 5000 characters.  If there is an issue with packaging in increase the field size limit, we'll reopen or create a new bug.

Does that work? Let me know before I close this issue @walt0019
