### ISSUE TITLE
[BUG] "Event is full display text" has misleading label

### ISSUE THREAD

**Issue by Scarrien** [SFDO-Community-Sprints/Summit-Events-App#411]
`Event is full display text` field on the Event object should have its label changed, because it's used for more than just the event being full (also displays when event registration is closed)

Recommend the label be changed to `Event Registration Closed Display Text` and help text be added to let the user know when this text will be displayed on the registration page.

**Comment by rdblake21** [comment]
Updating label to `Event Closed Display Text` with updated Description and Help Text to read:

`This text will appear if registration is unavailable due to the instance reaching capacity and/or the registration date passing. It will also appear if/when the related instances is not in an Active status.`

**Comment by tcdahlberg** [comment]
Included in beta release 0.28.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.28.0.2
