### ISSUE TITLE
[BUG] - Email Trigger and Guest Registrations

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community-Sprints/Summit-Events-App#463]
**Describe the bug**
When creating an event that allows Guest Registrations, if the Guest Registration, which created a registration record, doesn't have an email address, the email trigger seems to fail and the registration isn't able to be completed OR have the hosted registration records created.  Would like to update the email trigger to only send IF the Registrant Email field is populated.  Otherwise bypass the registration record

Use Case: For an event, someone may be registering other people, but the email is unknown. They should be able to input something (regardless of what it is) and have it create a registration record.

**To Reproduce**
1. Go to an event with Guest Registration questions. Don't include an email address
2. Complete a registration
3. See the error on the final confirmation page

**Expected behavior**
Expected to be able to register, have all appropriate registration record be created and an email only sends to the registrant.

**Screenshots**

**Additional context**
This would be additional should someone what to leverage Guest Registration for something like session submissions where they can submit multiple, but not have an email for each one.

**Comment by tcdahlberg** [comment]
@rdblake21, I wonder if we should also do a check for the registration field Guest_Host_Status__c not being "Hosted registrant." This would prevent hosted registrations from not getting emails. I personally, don't think we should send hosted registrants emails since they are not personally signing up for the event. This could lead to a SPAM factory (and not the kind in Austin, MN).

Haven't tested this yet, but have a branch with a possible fix here: 
https://github.com/SFDO-Community/Summit-Events-App/tree/BUG-463

**Comment by tcdahlberg** [comment]
Included in beta release 0.28.0.2

**Comment by tcdahlberg** [comment]
Included in production release 0.28.0.2
